version: '3.7'
services:
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
  #   container_name: es
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - ess

  db:
    image: postgres
    container_name: db
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      # - dbdata:/var/lib/postgresql/data
    environment:
      # POSTGRES_PASSWORD: 777
      POSTGRES_USER: es
      POSTGRES_DB: forum
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # networks:
    #   - ess
    secrets:
      - postgres_password
      - onemore

# volumes:
#   es-data:
#     driver: local
#
# networks:
#   ess:
#     driver: bridge
#     name: ess

secrets:
  postgres_password:
    file: ./secrets/postgres_password
  onemore:
    file: ./secrets/onemore
